{% set name = "pytest-cython" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytest-cython-{{ version }}.tar.gz
  sha256: 38d10faee6fc974a9240dccf9f85dc2534baf6be6e02a3fc77a9db8b6a5b0558

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - pytest >=4.6.0
    - python >=3.6

test:
  imports:
    - pytest_cython
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lgpage/pytest-cython
  summary: A plugin for testing Cython extension modules
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  dev_url: https://github.com/lgpage/pytest-cython

extra:
  recipe-maintainers:
    - jonashaag
    - lgpage
